# Generated by Django 4.1.3 on 2022-12-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='scope',
        ),
        migrations.AddField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.tag'),
            preserve_default=False,
        ),
    ]
